### ISSUE TITLE
setparam设置为6后对微信输入法不起作用

### ISSUE THREAD

**Issue by pheotry** [3biubiu/auto-shift-input#1]
希望支持下微信输入法
![图片](https://github.com/3biubiu/auto-shift-input/assets/43376740/b9921a9e-ad66-4f14-a3cf-9efa27c07817)

**Comment by 3biubiu** [comment]
OK

**Comment by 3biubiu** [comment]
我这边 没有发现这个问题，微信输入法 也是可以正常使用的
另外 修改配置后需要重新载入一下 vscode 窗口，配置才会生效

https://github.com/3biubiu/auto-shift-input/assets/63720467/2517fdb8-3089-4425-bf07-da33591b13bb
